In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("c:/Users/A/Intenship/Credit Card Approval Prediction System/credit_card1.csv")
df

,Gender,Age,Debt,Married,BankCustomer,Industry,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,Female,40.17,9.92,Yes,Yes,Financials,Yes,Yes,21.0,Yes,ByBirth,9524,26047.0,Approved
1,Female,NaN,10.96,Yes,No,Research,No,Yes,14.0,NaN,Temporary,42145,80906.0,Rejected
2,Female,NaN,5.01,No,Yes,CommunicationServices,Yes,No,19.0,No,ByBirth,62249,73958.0,Rejected
3,Male,23.00,9.26,No,Yes,Utilities,No,Yes,64.0,Yes,ByOtherMeans,26621,42632.0,Approved
4,female,30.67,22.60,No,No,Energy,Yes,Yes,NaN,Yes,Temporary,40799,90289.0,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,Female,44.54,1.74,No,Yes,Education,Yes,Yes,45.0,No,NaN,73348,11394.0,Approved
10196,Female,30.98,22.76,Yes,Yes,CommunicationServices,Yes,Yes,NaN,No,ByBirth,11225,72413.0,Approved
10197,Male,14.08,25.59,No,No,Materials,Yes,No,28.0,No,NaN,60800,82226.0,Rejected
10198,Male,47.31,13.28,Yes,No,NaN,No,No,2.0,Yes,ByBirth,27630,55498.0,Rejected
10199,Female,78.94,14.53,Yes,No,Education,Yes,Yes,36.0,Yes,ByBirth,52369,NaN,Approved

## Missing Value Check

In [3]:
df.isnull().sum()

Gender            512
Age               816
Debt              818
Married           507
BankCustomer      508
Industry          509
PriorDefault      507
Employed          516
CreditScore       825
DriversLicense    511
Citizen           512
ZipCode             0
Income            819
Approved            0
dtype: int64

## Numeric Value Fill

In [4]:
df['Age'].fillna(df['Age'].median(),inplace=True)
df['Income'].fillna(df['Income'].median(),inplace=True)
df['CreditScore'].fillna(df['CreditScore'].median(),inplace=True)

C:\Users\A\AppData\Local\Temp\ipykernel_21708\4180793034.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)
C:\Users\A\AppData\Local\Temp\ipykernel_21708\4180793034.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Income'].fillna(df['Income'].median(),inplace=True)
C:\Users\A\AppData\Local\Temp\ipykernel_21708\4180793034.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CreditScore'].fillna(df['CreditScore'].median(),inplace=True)

### Categorical

In [5]:
df['Industry'].fillna('Unknown',inplace=True)
df['Citizen'].fillna('Unknown',inplace=True)

C:\Users\A\AppData\Local\Temp\ipykernel_21708\3512038955.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Industry'].fillna('Unknown',inplace=True)
C:\Users\A\AppData\Local\Temp\ipykernel_21708\3512038955.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Citizen'].fillna('Unknown',inplace=True)

In [6]:
df

,Gender,Age,Debt,Married,BankCustomer,Industry,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,Female,40.17,9.92,Yes,Yes,Financials,Yes,Yes,21.0,Yes,ByBirth,9524,26047.0,Approved
1,Female,47.61,10.96,Yes,No,Research,No,Yes,14.0,NaN,Temporary,42145,80906.0,Rejected
2,Female,47.61,5.01,No,Yes,CommunicationServices,Yes,No,19.0,No,ByBirth,62249,73958.0,Rejected
3,Male,23.00,9.26,No,Yes,Utilities,No,Yes,64.0,Yes,ByOtherMeans,26621,42632.0,Approved
4,female,30.67,22.60,No,No,Energy,Yes,Yes,33.0,Yes,Temporary,40799,90289.0,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,Female,44.54,1.74,No,Yes,Education,Yes,Yes,45.0,No,Unknown,73348,11394.0,Approved
10196,Female,30.98,22.76,Yes,Yes,CommunicationServices,Yes,Yes,33.0,No,ByBirth,11225,72413.0,Approved
10197,Male,14.08,25.59,No,No,Materials,Yes,No,28.0,No,Unknown,60800,82226.0,Rejected
10198,Male,47.31,13.28,Yes,No,Unknown,No,No,2.0,Yes,ByBirth,27630,55498.0,Rejected
10199,Female,78.94,14.53,Yes,No,Education,Yes,Yes,36.0,Yes,ByBirth,52369,49471.0,Approved

In [7]:
df.duplicated().sum()

np.int64(145)

In [8]:
df=df.drop_duplicates()
df

,Gender,Age,Debt,Married,BankCustomer,Industry,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,Female,40.17,9.92,Yes,Yes,Financials,Yes,Yes,21.0,Yes,ByBirth,9524,26047.0,Approved
1,Female,47.61,10.96,Yes,No,Research,No,Yes,14.0,NaN,Temporary,42145,80906.0,Rejected
2,Female,47.61,5.01,No,Yes,CommunicationServices,Yes,No,19.0,No,ByBirth,62249,73958.0,Rejected
3,Male,23.00,9.26,No,Yes,Utilities,No,Yes,64.0,Yes,ByOtherMeans,26621,42632.0,Approved
4,female,30.67,22.60,No,No,Energy,Yes,Yes,33.0,Yes,Temporary,40799,90289.0,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10185,Male,68.59,7.79,Yes,Yes,Energy,No,Yes,42.0,No,ByBirth,34963,59812.0,Rejected
10186,female,53.36,1.87,No,Yes,communicationservices,Yes,Yes,14.0,Yes,ByOtherMeans,8000,21611.0,Approved
10190,Male,40.59,18.94,No,No,Transport,Yes,Yes,60.0,Yes,ByBirth,76164,91198.0,Approved
10196,Female,30.98,22.76,Yes,Yes,CommunicationServices,Yes,Yes,33.0,No,ByBirth,11225,72413.0,Approved
10198,Male,47.31,13.28,Yes,No,Unknown,No,No,2.0,Yes,ByBirth,27630,55498.0,Rejected

In [9]:
df.describe()

                Age         Debt   CreditScore       ZipCode         Income
count  10055.000000  9247.000000  10055.000000  10055.000000   10055.000000
mean      47.453790    14.738327     33.436798  50303.552561   51851.961313
std       18.800941    21.199420     18.711725  28737.610738   53982.259033
min        0.000000    -1.000000      0.000000    106.000000      -1.000000
25%       32.340000     6.880000     18.000000  25602.500000   26908.500000
50%       47.610000    13.910000     33.000000  50648.000000   49471.000000
75%       62.500000    21.055000     49.000000  75262.000000   72270.000000
max      120.000000   500.000000     67.000000  99998.000000  999999.000000

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,Female,40.17,9.92,Yes,Yes,Financials,Yes,Yes,21.0,Yes,ByBirth,9524,26047.0,Approved
1,Female,47.61,10.96,Yes,No,Research,No,Yes,14.0,NaN,Temporary,42145,80906.0,Rejected
2,Female,47.61,5.01,No,Yes,CommunicationServices,Yes,No,19.0,No,ByBirth,62249,73958.0,Rejected
3,Male,23.00,9.26,No,Yes,Utilities,No,Yes,64.0,Yes,ByOtherMeans,26621,42632.0,Approved
4,female,30.67,22.60,No,No,Energy,Yes,Yes,33.0,Yes,Temporary,40799,90289.0,Approved

In [12]:
df.isnull().sum()

Gender            502
Age                 0
Debt              808
Married           504
BankCustomer      503
Industry            0
PriorDefault      500
Employed          503
CreditScore         0
DriversLicense    504
Citizen             0
ZipCode             0
Income              0
Approved            0
dtype: int64

In [13]:
categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
categorical_columns

['Gender',
 'Married',
 'BankCustomer',
 'Industry',
 'PriorDefault',
 'Employed',
 'DriversLicense',
 'Citizen',
 'Approved']

In [14]:
df['Gender'].unique()

array(['Female', 'Male', 'female', 'male', nan], dtype=object)

In [15]:
df['Gender']  = df['Gender'].str.strip().str.title()

C:\Users\A\AppData\Local\Temp\ipykernel_21708\4095702392.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']  = df['Gender'].str.strip().str.title()

## Dropna

In [16]:
df.dropna(inplace=True)

C:\Users\A\AppData\Local\Temp\ipykernel_21708\1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [17]:
df.isnull().sum()

Gender            0
Age               0
Debt              0
Married           0
BankCustomer      0
Industry          0
PriorDefault      0
Employed          0
CreditScore       0
DriversLicense    0
Citizen           0
ZipCode           0
Income            0
Approved          0
dtype: int64

## Lable Encoding

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le=LabelEncoder()
le

LabelEncoder()

In [20]:
df['Gender_Encoder']=le.fit_transform(df['Gender'])
df['Gender_Encoder']

C:\Users\A\AppData\Local\Temp\ipykernel_21708\182248752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender_Encoder']=le.fit_transform(df['Gender'])

0        0
2        0
3        1
4        0
5        1
        ..
10185    1
10186    0
10190    1
10196    0
10198    1
Name: Gender_Encoder, Length: 6784, dtype: int64

In [21]:
df

,Gender,Age,Debt,Married,BankCustomer,Industry,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved,Gender_Encoder
0,Female,40.17,9.92,Yes,Yes,Financials,Yes,Yes,21.0,Yes,ByBirth,9524,26047.0,Approved,0
2,Female,47.61,5.01,No,Yes,CommunicationServices,Yes,No,19.0,No,ByBirth,62249,73958.0,Rejected,0
3,Male,23.00,9.26,No,Yes,Utilities,No,Yes,64.0,Yes,ByOtherMeans,26621,42632.0,Approved,1
4,Female,30.67,22.60,No,No,Energy,Yes,Yes,33.0,Yes,Temporary,40799,90289.0,Approved,0
5,Male,24.93,1.87,No,Yes,Research,Yes,No,29.0,Yes,bybirth,95060,4208.0,Rejected,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10185,Male,68.59,7.79,Yes,Yes,Energy,No,Yes,42.0,No,ByBirth,34963,59812.0,Rejected,1
10186,Female,53.36,1.87,No,Yes,communicationservices,Yes,Yes,14.0,Yes,ByOtherMeans,8000,21611.0,Approved,0
10190,Male,40.59,18.94,No,No,Transport,Yes,Yes,60.0,Yes,ByBirth,76164,91198.0,Approved,1
10196,Female,30.98,22.76,Yes,Yes,CommunicationServices,Yes,Yes,33.0,No,ByBirth,11225,72413.0,Approved,0
10198,Male,47.31,13.28,Yes,No,Unknown,No,No,2.0,Yes,ByBirth,27630,55498.0,Rejected,1

In [22]:
df['BankCustomer_Encoder']=le.fit_transform(df['BankCustomer'])

C:\Users\A\AppData\Local\Temp\ipykernel_21708\919132510.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BankCustomer_Encoder']=le.fit_transform(df['BankCustomer'])

In [23]:
df['Married_Encoder']=le.fit_transform(df['Married'])

C:\Users\A\AppData\Local\Temp\ipykernel_21708\17063228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Married_Encoder']=le.fit_transform(df['Married'])

In [24]:
df['Approved_encoder']=le.fit_transform(df['Approved'])

C:\Users\A\AppData\Local\Temp\ipykernel_21708\706354518.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Approved_encoder']=le.fit_transform(df['Approved'])

In [25]:
df['PriorDefault_Encoder']=le.fit_transform(df['PriorDefault'])

C:\Users\A\AppData\Local\Temp\ipykernel_21708\1934364089.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PriorDefault_Encoder']=le.fit_transform(df['PriorDefault'])

In [26]:
df['Employed_Encoder']=le.fit_transform(df['Employed'])

C:\Users\A\AppData\Local\Temp\ipykernel_21708\1768457678.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Employed_Encoder']=le.fit_transform(df['Employed'])

In [27]:
df['DriversLicense_Encoder']=le.fit_transform(df['DriversLicense'])

C:\Users\A\AppData\Local\Temp\ipykernel_21708\320248401.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DriversLicense_Encoder']=le.fit_transform(df['DriversLicense'])

In [28]:
df.head(1)

,Gender,Age,Debt,Married,BankCustomer,Industry,PriorDefault,Employed,CreditScore,DriversLicense,...,ZipCode,Income,Approved,Gender_Encoder,BankCustomer_Encoder,Married_Encoder,Approved_encoder,PriorDefault_Encoder,Employed_Encoder,DriversLicense_Encoder
0,Female,40.17,9.92,Yes,Yes,Financials,Yes,Yes,21.0,Yes,...,9524,26047.0,Approved,0,1,1,0,1,1,1

In [29]:
# --- Income માટે Outlier Treatment (IQR Method) ---
Q1_inc = df['Income'].quantile(0.25)
Q3_inc = df['Income'].quantile(0.75)
IQR_inc = Q3_inc - Q1_inc

lower_inc = Q1_inc - 1.5 * IQR_inc
upper_inc = Q3_inc + 1.5 * IQR_inc

df['Income'] = df['Income'].clip(lower=lower_inc, upper=upper_inc)

# --- Debt માટે Outlier Treatment ---
Q1_debt = df['Debt'].quantile(0.25)
Q3_debt = df['Debt'].quantile(0.75)
IQR_debt = Q3_debt - Q1_debt

lower_debt = Q1_debt - 1.5 * IQR_debt
upper_debt = Q3_debt + 1.5 * IQR_debt


df['Debt'] = df['Debt'].clip(lower=lower_debt, upper=upper_debt)

C:\Users\A\AppData\Local\Temp\ipykernel_21708\2484536799.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Income'] = df['Income'].clip(lower=lower_inc, upper=upper_inc)
C:\Users\A\AppData\Local\Temp\ipykernel_21708\2484536799.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Debt'] = df['Debt'].clip(lower=lower_debt, upper=upper_debt)

In [30]:
df.to_csv('c:/Users/A/Intenship/Credit Card Approval Prediction System/clean_dataset.csv',index=False)

In [31]:
df

,Gender,Age,Debt,Married,BankCustomer,Industry,PriorDefault,Employed,CreditScore,DriversLicense,...,ZipCode,Income,Approved,Gender_Encoder,BankCustomer_Encoder,Married_Encoder,Approved_encoder,PriorDefault_Encoder,Employed_Encoder,DriversLicense_Encoder
0,Female,40.17,9.92,Yes,Yes,Financials,Yes,Yes,21.0,Yes,...,9524,26047.0,Approved,0,1,1,0,1,1,1
2,Female,47.61,5.01,No,Yes,CommunicationServices,Yes,No,19.0,No,...,62249,73958.0,Rejected,0,1,0,1,1,0,0
3,Male,23.00,9.26,No,Yes,Utilities,No,Yes,64.0,Yes,...,26621,42632.0,Approved,1,1,0,0,0,1,1
4,Female,30.67,22.60,No,No,Energy,Yes,Yes,33.0,Yes,...,40799,90289.0,Approved,0,0,0,0,1,1,1
5,Male,24.93,1.87,No,Yes,Research,Yes,No,29.0,Yes,...,95060,4208.0,Rejected,1,1,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10185,Male,68.59,7.79,Yes,Yes,Energy,No,Yes,42.0,No,...,34963,59812.0,Rejected,1,1,1,1,0,1,0
10186,Female,53.36,1.87,No,Yes,communicationservices,Yes,Yes,14.0,Yes,...,8000,21611.0,Approved,0,1,0,0,1,1,1
10190,Male,40.59,18.94,No,No,Transport,Yes,Yes,60.0,Yes,...,76164,91198.0,Approved,1,0,0,0,1,1,1
10196,Female,30.98,22.76,Yes,Yes,CommunicationServices,Yes,Yes,33.0,No,...,11225,72413.0,Approved,0,1,1,0,1,1,0
10198,Male,47.31,13.28,Yes,No,Unknown,No,No,2.0,Yes,...,27630,55498.0,Rejected,1,0,1,1,0,0,1

In [32]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)